### ISSUE TITLE
cpphs-1.19 compatibility

### ISSUE THREAD

**Issue by nomeata** [luqui/hothasktags#23]
Hi,

cpphs-1.19 has been released, please consider upgrading hothasktags and uploading that to hackage.

Also, consider joining stackage (http://www.stackage.org/authors) to streamline the process. This would help downstream packages (e.g. Debian) a lot.

Thanks,
Joachim

**Comment by luqui** [comment]
I upgraded hothasktags dependency and uploaded.  Thanks for the report.
