### ISSUE TITLE
Please make compatible with cpphs >=1.20

### ISSUE THREAD

**Issue by spwhitton** [luqui/hothasktags#29]
It would be great if hothasktags were compatible with cpphs >=1.20 (the current release is 1.20.1).  Thanks.

**Comment by luqui** [comment]
Hi Sean,

I'm not really coding much these days.  I tried to update the dependency but there were some nontrivial errors (for me right now, for someone in the flow they're probably easy).  I'll review a patch but not up for coding atm.

Thanks for the report.
